# Generated by Django 3.0.5 on 2020-05-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_hash', models.CharField(blank=True, max_length=100)),
                ('merkle_hash', models.CharField(blank=True, max_length=100)),
                ('this_hash', models.CharField(blank=True, max_length=100)),
                ('nonce', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MiningInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_hash', models.CharField(blank=True, max_length=100)),
                ('last_block_id', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('party_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=100)),
                ('party_logo', models.CharField(max_length=500)),
                ('candidate_name', models.CharField(blank=True, max_length=100)),
                ('candidate_profile_pic', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('uuid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vote_party_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('block_id', models.CharField(max_length=10, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VoteBackup',
            fields=[
                ('uuid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vote_party_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('block_id', models.CharField(max_length=10, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('uuid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('pincode', models.CharField(max_length=6)),
                ('region', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('vote_done', models.BooleanField(default=False)),
            ],
        ),
    ]
